self_id              = 0
data_dirs            = ["data/d0", "data/d1", "data/d2", "data/d3"]
s3_addr              = "0.0.0.0:9000"
rpc_addr             = "127.0.0.1:9100"
set_drive_count      = 4
default_parity_count = 1
region               = "us-east-1"

[[credentials]]
access_key = "openlakeadmin"
secret_key = "openlakeadmin"

[[nodes]]
id         = 0
rpc_addr   = "127.0.0.1:9100"
disk_count = 4
